language: python

sudo: required

services:
  - docker
 
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t whucecil/friendlyhello . 
  - docker push whucecil/friendlyhello
  
  
